version: "2"
services:
  zentao:
    image: registry.cn-hangzhou.aliyuncs.com/tandaly/zentao
    container_name: zentao
    privileged: true
    restart: always
    ports:
      - "888:80"
    networks:
      frontend_zentao:
      backend_zentao:
    volumes:
      - volume_zentao_data:/opt/zbox


networks:
  frontend_zentao:
  backend_zentao:

volumes:
  volume_zentao_data:

